version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - user_api_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dev_api_admin
      POSTGRES_PASSWORD: dev_api_admin
      POSTGRES_DB: gia_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - user_api_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_api_admin -d gia_dev -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  user_api_network:
    driver: bridge

volumes:
  postgres_data:
